from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
DEFAULT_OUTPUT = ROOT / "docs" / "agent_skills_index.md"


@dataclass(frozen=True)
class SkillSummary:
    name: str
    title: str
    purpose: str
    resource_count: int


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the TreLLM agent skill index.")
    parser.add_argument("skills_dir", nargs="?", default=str(SKILLS_DIR), help="Directory containing skill folders.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Markdown output path.")
    parser.add_argument("--check", action="store_true", help="Fail if the existing index is stale.")
    args = parser.parse_args(argv)

    output = Path(args.output)
    markdown = render_index(discover_skills(Path(args.skills_dir)))
    if args.check:
        if not output.exists():
            print(f"Skill index is missing: {output}")
            return 1
        existing = output.read_text(encoding="utf-8")
        if existing != markdown:
            print(f"Skill index is stale: {output}")
            return 1
        print(f"Skill index is current: {output}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    print(f"Wrote {output}")
    return 0


def discover_skills(skills_dir: Path = SKILLS_DIR) -> list[SkillSummary]:
    rows = []
    for skill_dir in sorted(path for path in skills_dir.iterdir() if path.is_dir()):
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            continue
        text = skill_file.read_text(encoding="utf-8")
        resources_dir = skill_dir / "resources"
        resource_count = len(list(resources_dir.glob("*"))) if resources_dir.exists() else 0
        rows.append(
            SkillSummary(
                name=skill_dir.name,
                title=_title(text, skill_dir.name),
                purpose=_section_summary(text, "Purpose"),
                resource_count=resource_count,
            )
        )
    return rows


def render_index(skills: list[SkillSummary]) -> str:
    lines = [
        "# TreLLM Agent Skills Index",
        "",
        "This file is generated by `python scripts/build_skill_index.py`.",
        "Skills are TreLLM repository workflows for audit, reproduction, calibration,",
        "claim-boundary review, and plugin authoring. They are not runtime",
        "trading prompts and should not be injected into benchmarked agents",
        "unless recorded in the TreLLM run manifest.",
        "",
        "| Skill | Purpose | Resources |",
        "| --- | --- | ---: |",
    ]
    for skill in skills:
        lines.append(
            f"| [`{skill.name}`](../skills/{skill.name}/SKILL.md) | "
            f"{_escape_table(skill.purpose or skill.title)} | {skill.resource_count} |"
        )
    lines.extend(
        [
            "",
            "## Contract",
            "",
            "Every skill must include a purpose, required inputs, safety boundary,",
            "workflow, output contract, validation commands, and claim-boundary",
            "language. Run `python scripts/validate_skill_contract.py` before",
            "submitting skill changes.",
            "",
        ]
    )
    return "\n".join(lines)


def _title(text: str, fallback: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def _section_summary(text: str, heading: str) -> str:
    marker = f"## {heading}"
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if line.strip() != marker:
            continue
        paragraph = []
        for candidate in lines[index + 1 :]:
            if candidate.startswith("## "):
                break
            if not candidate.strip() and paragraph:
                break
            if candidate.strip():
                paragraph.append(candidate.strip())
        return " ".join(paragraph)
    return ""


def _escape_table(value: str) -> str:
    return value.replace("|", "\\|")


if __name__ == "__main__":
    raise SystemExit(main())
