from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


COMMANDS = [
    {
        "id": "trajectory",
        "argv": [sys.executable, "examples/audit_trajectory_walkthrough.py"],
        "description": "Generate the deterministic replayable trajectory.",
    },
    {
        "id": "audit_report",
        "argv": [sys.executable, "scripts/render_audit_report.py"],
        "description": "Render the replayable audit report HTML.",
    },
    {
        "id": "agent_autopsy",
        "argv": [sys.executable, "scripts/render_agent_autopsy_dashboard.py"],
        "description": "Render the Agent Autopsy Dashboard.",
    },
    {
        "id": "failure_autopsy",
        "argv": [sys.executable, "scripts/run_failure_autopsy.py"],
        "description": "Classify trajectory failure modes.",
    },
    {
        "id": "validate_submission",
        "argv": [
            sys.executable,
            "-m",
            "tradearena.cli",
            "validate-submission",
            "examples/benchmark_submissions/example_redacted_submission.json",
        ],
        "description": "Validate a benchmark row manifest.",
    },
    {
        "id": "release_readiness",
        "argv": [sys.executable, "scripts/check_release_readiness.py"],
        "description": "Run the public release-readiness gate.",
    },
]

ARTIFACTS = [
    "outputs/examples/audit_walkthrough_trajectory.json",
    "outputs/examples/audit_report.html",
    "outputs/examples/agent_autopsy_dashboard.html",
    "outputs/examples/failure_autopsy.json",
    "outputs/examples/failure_autopsy.md",
    "examples/benchmark_submissions/example_redacted_submission.json",
]


def main() -> int:
    parser = argparse.ArgumentParser(description="Run and record a 15-minute external reproduction pack.")
    parser.add_argument("--output-dir", default="outputs/reproduction/v0_2")
    parser.add_argument("--skip-commands", action="store_true", help="Only record hashes for existing artifacts.")
    args = parser.parse_args()

    output_dir = ROOT / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    command_results = []
    if not args.skip_commands:
        for command in COMMANDS:
            command_results.append(_run_command(command))
    else:
        command_results = [{**command, "returncode": None, "skipped": True} for command in COMMANDS]

    hash_run = _hash_trajectory(ROOT / "outputs/examples/audit_walkthrough_trajectory.json")
    manifest = {
        "schema": "tradearena_external_reproduction_pack_v1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "repository": "https://github.com/weich97/TreLLM-public",
        "commit_or_tag": _git(["rev-parse", "HEAD"]),
        "git_status_short": _git(["status", "--short"]),
        "python": {
            "version": platform.python_version(),
            "implementation": platform.python_implementation(),
            "executable": sys.executable,
            "platform": platform.platform(),
        },
        "commands": command_results,
        "artifacts": [_artifact_record(ROOT / rel) for rel in ARTIFACTS],
        "trajectory_hash": hash_run,
        "live_api_used": False,
        "market_data_used": "deterministic synthetic data generated by examples/audit_trajectory_walkthrough.py",
        "private_fills_used": False,
        "notes": (
            "This pack is the no-key reproduction path. Provider-backed rows and calibrated execution "
            "reports should attach their own manifests with live_api_used and data provenance set accordingly."
        ),
    }
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (output_dir / "README.md").write_text(_render_readme(manifest), encoding="utf-8")
    print(f"Wrote {_display_path(manifest_path)}")
    print(f"Wrote {_display_path(output_dir / 'README.md')}")
    failed_summary = summarize_failed_commands(command_results)
    if failed_summary:
        print(failed_summary, file=sys.stderr)
        return 1
    return 0


def _run_command(command: dict[str, Any]) -> dict[str, Any]:
    result = subprocess.run(command["argv"], cwd=ROOT, capture_output=True, text=True)
    return {
        "id": command["id"],
        "description": command["description"],
        "argv": command["argv"],
        "returncode": result.returncode,
        "stdout_tail": result.stdout[-2000:],
        "stderr_tail": result.stderr[-2000:],
    }


def summarize_failed_commands(command_results: list[dict[str, Any]]) -> str:
    failed = [result for result in command_results if result.get("returncode") not in {0, None}]
    if not failed:
        return ""

    lines = ["Failed reproduction commands:"]
    for result in failed:
        command_id = result.get("id", "<unknown>")
        lines.append(f"- {command_id} returned {result.get('returncode')}")
        stdout_tail = str(result.get("stdout_tail", "")).strip()
        stderr_tail = str(result.get("stderr_tail", "")).strip()
        if stdout_tail:
            lines.append("  stdout tail:")
            lines.extend(f"    {line}" for line in stdout_tail.splitlines())
        if stderr_tail:
            lines.append("  stderr tail:")
            lines.extend(f"    {line}" for line in stderr_tail.splitlines())
    return "\n".join(lines)


def _hash_trajectory(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"error": f"missing trajectory: {path.relative_to(ROOT)}"}
    from tradearena.core.reproducibility import hash_trajectory_file

    return hash_trajectory_file(path)


def _artifact_record(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"path": path.relative_to(ROOT).as_posix(), "exists": False}
    return {
        "path": path.relative_to(ROOT).as_posix(),
        "exists": True,
        "bytes": path.stat().st_size,
        "sha256": _sha256(path),
    }


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return "sha256:" + digest.hexdigest()


def _display_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _git(args: list[str]) -> str:
    try:
        result = subprocess.run(_git_command(args), cwd=ROOT, check=True, capture_output=True, text=True)
        return result.stdout.strip()
    except Exception:
        return ""


def _git_command(args: list[str]) -> list[str]:
    return ["git", "-c", f"safe.directory={ROOT.as_posix()}", *args]


def _render_readme(manifest: dict[str, Any]) -> str:
    failed_commands = _failed_command_ids(manifest)
    missing_artifacts = _missing_artifact_paths(manifest)
    trajectory_hash = _trajectory_reproducibility_hash(manifest)
    lines = [
        "# TreLLM v0.2 External Reproduction Pack",
        "",
        "This directory is generated by:",
        "",
        "```bash",
        "python scripts/run_external_reproduction_pack.py",
        "```",
        "",
        "It records the commit, Python environment, commands, artifact hashes, and trajectory hash for the no-key reproduction path.",
        "",
        "## Environment",
        "",
        f"- Commit/tag: `{manifest['commit_or_tag']}`",
        f"- Python: `{manifest['python']['version']}`",
        f"- Platform: `{manifest['python']['platform']}`",
        f"- Live API used: `{manifest['live_api_used']}`",
        f"- Market data: {manifest['market_data_used']}",
        f"- Private fills used: `{manifest['private_fills_used']}`",
        "",
        "## Commands",
        "",
    ]
    for command in manifest["commands"]:
        lines.append(f"- `{command['id']}`: `{' '.join(command['argv'])}` -> `{command.get('returncode')}`")
    lines.extend(["", "## Artifacts", ""])
    for artifact in manifest["artifacts"]:
        status = "present" if artifact.get("exists") else "missing"
        digest = artifact.get("sha256", "")
        lines.append(f"- `{artifact['path']}`: {status} {digest}")
    lines.extend(
        [
            "",
            "## Trajectory Hash",
            "",
            "```json",
            json.dumps(manifest["trajectory_hash"], indent=2, sort_keys=True),
            "```",
            "",
            "## Suggested Issue Text",
            "",
            "```markdown",
            f"Environment: {manifest['python']['platform']} / Python {manifest['python']['version']}",
            f"Commit/tag: {manifest['commit_or_tag']}",
            f"Trajectory hash: {trajectory_hash}",
            "Manifest: outputs/reproduction/v0_2/manifest.json",
            f"Commands failed: {', '.join(failed_commands) if failed_commands else 'none'}",
            f"Missing artifacts: {', '.join(missing_artifacts) if missing_artifacts else 'none'}",
            "No live APIs or private fills were used.",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _failed_command_ids(manifest: dict[str, Any]) -> list[str]:
    commands = manifest.get("commands", []) if isinstance(manifest.get("commands"), list) else []
    return [str(command.get("id", "")) for command in commands if command.get("returncode") not in {0, None}]


def _missing_artifact_paths(manifest: dict[str, Any]) -> list[str]:
    artifacts = manifest.get("artifacts", []) if isinstance(manifest.get("artifacts"), list) else []
    return [str(artifact.get("path", "")) for artifact in artifacts if not artifact.get("exists")]


def _trajectory_reproducibility_hash(manifest: dict[str, Any]) -> str:
    trajectory_hash = manifest.get("trajectory_hash", {})
    if not isinstance(trajectory_hash, dict):
        return ""
    return str(trajectory_hash.get("reproducibility_hash", ""))


if __name__ == "__main__":
    raise SystemExit(main())
